services:
  local-test-db:
    image: mongo:latest
    restart: always
    ports:
      - 8080:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: nodemailer-local-db
    networks:
      - nodemailer-local
networks:
  nodemailer-local:
    driver: bridge
